# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a6d3b601205766c15f6e3e16fabdfe969472bc2b8d5af975dfb97d6cdf6bdb5877d1df1524cfb0d3ee85b5e870b6ad8d25c74b930f94226a2e210c54ff1ada3
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  cloud_name: djywhagdm
  enhance_image_tag: true
  static_image_support: false

test:
  secret_key_base: fbd4b4da32396aa9e4c670b99107666e9847ce9967bc92a2f58381c11791a320101a64bd0f2817b942bda425b9c37a139d484aaf5e60d19417f36dd730d56ab7
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  cloud_name: djywhagdm
  enhance_image_tag: true
  static_image_support: false

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  cloud_name: djywhagdm
  enhance_image_tag: true
  static_image_support: false
